// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2_warmUp;

namespace _2_warmUp.Migrations
{
    [DbContext(typeof(GloriaContext))]
    partial class GloriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("_2_warmUp.Artist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("_2_warmUp.JubileeStreet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Various")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isBand")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ArtistID")
                        .IsUnique();

                    b.ToTable("JubileeStreets");
                });

            modelBuilder.Entity("_2_warmUp.Song", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Duration")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ArtistID");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("_2_warmUp.JubileeStreet", b =>
                {
                    b.HasOne("_2_warmUp.Artist", "Artist")
                        .WithOne("JubileeStreet")
                        .HasForeignKey("_2_warmUp.JubileeStreet", "ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("_2_warmUp.Song", b =>
                {
                    b.HasOne("_2_warmUp.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("_2_warmUp.Artist", b =>
                {
                    b.Navigation("JubileeStreet");

                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
