// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3_ManyToMany;

namespace _3_ManyToMany.Migrations
{
    [DbContext(typeof(GloriaContext))]
    [Migration("20211029145528_createDB")]
    partial class createDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("MuhendisProje", b =>
                {
                    b.Property<int>("MuhendislerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjelerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("MuhendislerID", "ProjelerID");

                    b.HasIndex("ProjelerID");

                    b.ToTable("MuhendisProje");
                });

            modelBuilder.Entity("_3_ManyToMany.Muhendis", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Brans")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MuhendisProjeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("MuhendisProjeID");

                    b.ToTable("Muhendisler");
                });

            modelBuilder.Entity("_3_ManyToMany.MuhendisProje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("MuhendislerProjeler");
                });

            modelBuilder.Entity("_3_ManyToMany.Proje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Baslangic")
                        .HasColumnType("REAL");

                    b.Property<double>("Bitis")
                        .HasColumnType("REAL");

                    b.Property<int>("MuhendisID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MuhendisProjeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("MuhendisProjeID");

                    b.ToTable("Projeler");
                });

            modelBuilder.Entity("MuhendisProje", b =>
                {
                    b.HasOne("_3_ManyToMany.Muhendis", null)
                        .WithMany()
                        .HasForeignKey("MuhendislerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_3_ManyToMany.Proje", null)
                        .WithMany()
                        .HasForeignKey("ProjelerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_3_ManyToMany.Muhendis", b =>
                {
                    b.HasOne("_3_ManyToMany.MuhendisProje", null)
                        .WithMany("Muhendisler")
                        .HasForeignKey("MuhendisProjeID");
                });

            modelBuilder.Entity("_3_ManyToMany.Proje", b =>
                {
                    b.HasOne("_3_ManyToMany.MuhendisProje", null)
                        .WithMany("Projeler")
                        .HasForeignKey("MuhendisProjeID");
                });

            modelBuilder.Entity("_3_ManyToMany.MuhendisProje", b =>
                {
                    b.Navigation("Muhendisler");

                    b.Navigation("Projeler");
                });
#pragma warning restore 612, 618
        }
    }
}
